'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    'header.title': 'NOVA TECH',
    'header.subtitle': 'LUCAS TORTELLI - DESENVOLVEDOR FULL-STACK',
    'header.description': '🚀 Portfólio full-stack — projetos em web, inteligência artificial e soluções digitais',
    'header.buttons.projects': 'Ver Projetos',
    'header.buttons.contact': 'Contato',
    'header.intro': 'Bem-vindo ao meu portfólio profissional. Aqui você encontrará os principais projetos que desenvolvi ou estou desenvolvendo atualmente.',
    'profile.title': 'Evolução Tecnológica',
    'profile.description': 'Desenvolvedor especializado em tecnologias emergentes, inteligência artificial e arquiteturas cloud-native. Com mais de 5 anos transformando ideias em soluções digitais revolucionárias.',
    'profile.skills.security.title': 'Segurança',
    'profile.skills.security.description': 'Implementação de protocolos avançados',
    'profile.skills.performance.title': 'Performance',
    'profile.skills.performance.description': 'Otimização de alta performance',
    'profile.techStack': 'Stack Tecnológico',
    'profile.contactButton': 'Vamos Conversar',
    'profile.image.alt': 'Desenvolvedor Nova Tech',
    'profile.whatsapp.message': 'Olá! Vim pelo seu portfólio e gostaria de conversar sobre um projeto.',
    'contact.title': 'Vamos Construir o Futuro',
    'contact.subtitle': 'Entre em contato para discutir projetos inovadores e soluções tecnológicas de ponta',
    'contact.connect': 'Conecte-se Comigo',
    'contact.form.title': 'Envie uma Mensagem',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Assunto',
    'contact.form.message': 'Mensagem',
    'contact.form.namePlaceholder': 'Seu nome',
    'contact.form.emailPlaceholder': 'seu@email.com',
    'contact.form.subjectPlaceholder': 'Assunto da mensagem',
    'contact.form.messagePlaceholder': 'Descreva seu projeto ou ideia...',
    'contact.form.sendButton': 'Enviar Mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
    'contact.form.error': 'Erro ao enviar mensagem',
    'contact.form.connectionError': 'Erro de conexão. Tente novamente.',
    'contact.quote': 'A tecnologia não é apenas uma ferramenta, é a linguagem do futuro',
    'contact.cv.title': 'CV',
    'contact.cv.description': 'Download PDF',
    'projects.title': 'Projetos Inovadores',
    'projects.subtitle': 'Soluções tecnológicas que redefinem o futuro digital',
    'projects.viewMore': 'Ver Mais Projetos',
    'projects.code': 'Código',
    'projects.demo': 'Demo',
    'projects.aurum.title': 'Aurum - Gestão da sua Carteira de Investimentos',
    'projects.aurum.description': 'Plataforma completa de gestão de investimentos com cotações em tempo real. Monitore criptomoedas, ações brasileiras e internacionais, acompanhando ganhos e perdas instantaneamente. Interface intuitiva com gráficos interativos e relatórios detalhados de performance.',
    'projects.status.completed': 'Concluído',
    'projects.status.pending': 'Em desenvolvimento',
    'projects.ai.title': 'Dashboard de Redes Neurais IA',
    'projects.ai.description': 'Sistema avançado de monitoramento e controle de redes neurais com interface futurista e análise em tempo real.',
    'projects.blockchain.title': 'Plataforma DeFi Blockchain',
    'projects.blockchain.description': 'Plataforma descentralizada para finanças digitais com smart contracts e interface Web3 intuitiva.',
    'projects.quantum.title': 'App Móvel Quântico',
    'projects.quantum.description': 'Aplicativo móvel com computação quântica simulada e interface holográfica 3D.',
    'projects.metaverse.title': 'Portal Web Metaverso',
    'projects.metaverse.description': 'Portal web para acesso ao metaverso com realidade virtual e interações 3D imersivas.',
    'footer.brand.description': 'Desenvolvendo o futuro com tecnologia de ponta e inovação constante',
    'footer.tech.title': 'Tecnologias',
    'footer.vision.title': 'Visão',
    'footer.vision.description': 'Transformar ideias em realidade digital através de soluções tecnológicas inovadoras que moldam o futuro',
    'footer.madeWith': 'Feito com',
    'footer.and': 'e',
    'footer.by': 'por Nova Tech',
    'footer.copyright': '© 2024 Nova Tech. Inovação sem limites.',
    'guide.title': 'Aurum',
    'guide.overview.title': 'Visão Geral',
    'guide.overview.description': 'Aurum FrontEnd — Real‑time Investment Dashboard. Frontend React para acompanhamento de carteira e cotações em tempo real, com foco em resiliência de rede, UX responsiva e arquitetura extensível. Integra WebSockets para streaming de mercado e API REST para operações seguras.',
    'guide.architecture.title': 'Arquitetura e Stack',
    'guide.architecture.stack': 'Stack: React + Vite, Context API + Hooks, Socket.IO Client, Fetch API (retries/timeouts), Tailwind CSS, estrutura própria de traduções (PT/EN).',
    'guide.architecture.layers': 'Camadas:',
    'guide.architecture.requestMonitor': 'src/components/contexts/RequestMonitorContext.jsx: singleton do socket, deduplicação de requisições, timeouts globais.',
    'guide.architecture.backendClient': 'src/api/backendClient.js: retriable fetch, timeouts, propagação de erro estruturado (status, message).',
    'guide.architecture.pages': 'Páginas:',
    'guide.architecture.pages.dashboard': 'Dashboard.jsx — Gráficos com atualizações on-visibility',
    'guide.architecture.pages.marketTicker': 'MarketTicker.jsx — Tickers em marquee atualizados em tempo real com requisições gerenciadas pelo backend',
    'guide.architecture.pages.login': 'Login.jsx — Login com credenciais/Google Authenticator com tradutores de erros/validações provenientes do backend',
    'guide.architecture.pages.portfolio': 'Portfolio.jsx — Portfolio com detalhamento dos investimentos',
    'guide.architecture.pages.liquidityModal': 'LiquidityModal.jsx — Modal de liquidez com gráficos e informativos sobre o tempo de liquidez do investimento',
    'guide.architecture.pages.portfolioModal': 'PortfolioModal.jsx — Detalhamento de cada investimento',
    'guide.architecture.pages.addInvestment': 'AddInvestment.jsx — Incluir investimento em cripto, ações brasileiras e americanas',
    'guide.architecture.languageContext': 'LanguageContext.jsx: traduções de códigos HTTP e mensagens genéricas.',
    'guide.features.title': 'Principais Funcionalidades',
    'guide.features.realtime': 'Realtime: Ticker e atualização de preços via Socket.IO (reconexão controlada, backoff, event‑driven).',
    'guide.features.deduplication': 'Deduplicação de requisições: mesma chave lógica → uma chamada, múltiplos consumidores; timeout global de 60s.',
    'guide.features.resilience': 'Resiliência de rede: fallback de URL de socket, espera por conexão, tratamento consistente de 4xx/5xx.',
    'guide.features.errors': 'Erro estruturado + estrutura própria de traduções: backend retorna (status, message); UI traduz por status (ex.: error.401) com fallback.',
    'guide.features.ux': 'UX: estados de carregamento, filtragem de mensagens técnicas (ex.: oculta "socket não conectado"), dark mode otimizado.',
    'guide.decisions.title': 'Decisões Técnicas Relevantes',
    'guide.decisions.singleton': 'Singleton de Socket: isConnectingRef + checagens de connected evitam conexões duplicadas.',
    'guide.decisions.timeouts': 'Timeouts e Retries: AbortController/timeouts no fetch; timeout global nos fluxos WebSocket.',
    'guide.decisions.standardized': 'Erros padronizados: sempre lança objeto com status/message para previsibilidade.',
    'guide.decisions.configuration': 'Configuração robusta: getSocketUrl deriva fallback de API_URL e ambiente (dev/prod).',
    'guide.security.title': 'Segurança e Boas Práticas',
    'guide.security.keys': 'Sem chaves no client: variáveis via ambiente; sem lógica sensível no frontend.',
    'guide.security.isolation': 'Isolamento de erros: mensagens internas não vazam; UI filtra ruído técnico.',
    'guide.security.architecture': 'Arquitetura escalável: contexts especializados, funções puras para APIs, componentes desacoplados.',
    'guide.performance.title': 'Métricas e Performance (indicativas)',
    'guide.performance.connections': 'Conexões WebSocket únicas por sessão/componente.',
    'guide.performance.redundancy': 'Queda de chamadas redundantes com deduplicação.',
    'guide.performance.latency': 'Latência percebida reduzida via streaming + pré‑carregamento sob visibilidade.',
    'guide.review.title': 'O que revisar no código (para avaliadores)',
    'guide.review.requestMonitor': 'RequestMonitorContext.jsx: ciclo de vida do socket, mapas de promessas deduplicadas, limpeza de timeouts.',
    'guide.review.backendClient': 'backendClient.js: política de retries, timeouts, normalização de erro.',
    'guide.review.login': 'Login.jsx: tradução por código HTTP, UI de erro acessível.',
    'guide.review.config': 'config.js: derivação de socketUrl e fallbacks.',
    'guide.screenshots.title': 'Roteiro de Prints (sugestão)',
    'guide.screenshots.login': 'Login (PT/EN) — "Tratamento de erros por código HTTP com estrutura própria de traduções e dark mode."',
    'guide.screenshots.dashboard': 'Dashboard — "Resumo de portfólio com atualização baseada em visibilidade da aba."',
    'guide.screenshots.marketTicker': 'Market Ticker — "Streaming de cotações via Socket.IO com reconexão controlada."',
    'guide.screenshots.liquidityModal': 'Modal de Liquidez — "Interações consistentes; fechamento corrigido e estados claros."',
    'guide.screenshots.console': 'Console (devtools) — "Deduplicação de requisições: mesma chave, uma chamada, múltiplos consumidores."',
    'guide.screenshots.network': 'Network (devtools) — "Fallback de socketUrl funcional; ausência de conexões duplicadas."',
    'guide.screenshots.structure': 'Estrutura do projeto — "Separação de contexts, API client e páginas para escalabilidade."',
    'guide.differentials.title': 'Diferenciais',
    'guide.differentials.robustness': 'Robustez de rede acima da média: evita race conditions de sockets, pendências de promessa e loops de reconexão.',
    'guide.differentials.ux': 'Erro e UX de nível produto: mensagens amigáveis para usuário, diagnósticos claros para dev.',
    'guide.differentials.evolution': 'Pronto para evolução: troca de provedores de dados e novas features sem romper contratos internos.'
  },
  en: {
    'header.title': 'NOVA TECH',
    'header.subtitle': 'LUCAS TORTELLI - FULL-STACK DEVELOPER',
    'header.description': '🚀 Full-stack portfolio — showcasing my work in web, AI and software solutions',
    'header.buttons.projects': 'View Projects',
    'header.buttons.contact': 'Contact',
    'header.intro': "Welcome to my professional portfolio. Here you'll find the main projects I've developed or am currently working on.",
    'profile.title': 'Technological Evolution',
    'profile.description': 'Developer specialized in emerging technologies, artificial intelligence and cloud-native architectures. With over 5 years transforming ideas into revolutionary digital solutions.',
    'profile.skills.security.title': 'Security',
    'profile.skills.security.description': 'Advanced protocol implementation',
    'profile.skills.performance.title': 'Performance',
    'profile.skills.performance.description': 'High-performance optimization',
    'profile.techStack': 'Tech Stack',
    'profile.contactButton': "Let's Talk",
    'profile.image.alt': 'Nova Tech Developer',
    'profile.whatsapp.message': 'Hello! I came through your portfolio and would like to discuss a project.',
    'contact.title': "Let's Build the Future",
    'contact.subtitle': 'Get in touch to discuss innovative projects and cutting-edge technological solutions',
    'contact.connect': 'Connect With Me',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subjectPlaceholder': 'Message subject',
    'contact.form.messagePlaceholder': 'Describe your project or idea...',
    'contact.form.sendButton': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We will contact you soon.',
    'contact.form.error': 'Error sending message',
    'contact.form.connectionError': 'Connection error. Please try again.',
    'contact.quote': 'Technology is not just a tool, it is the language of the future',
    'contact.cv.title': 'CV',
    'contact.cv.description': 'Download PDF',
    'projects.title': 'Innovative Projects',
    'projects.subtitle': 'Technological solutions that redefine the digital future',
    'projects.viewMore': 'View More Projects',
    'projects.code': 'Code',
    'projects.demo': 'Demo',
    'projects.aurum.title': 'Aurum - Your Investment Management',
    'projects.aurum.description': 'Investment platform with real-time quotes for cryptocurrencies, Brazilian stocks, and international equities. Track gains and losses with interactive charts and detailed performance reports.',
    'projects.status.completed': 'Completed',
    'projects.status.pending': 'In Progress',
    'projects.ai.title': 'AI Neural Network Dashboard',
    'projects.ai.description': 'Advanced neural network monitoring and control system with futuristic interface and real-time analysis.',
    'projects.blockchain.title': 'Blockchain DeFi Platform',
    'projects.blockchain.description': 'Decentralized platform for digital finance with smart contracts and intuitive Web3 interface.',
    'projects.quantum.title': 'Quantum Mobile App',
    'projects.quantum.description': 'Mobile application with simulated quantum computing and 3D holographic interface.',
    'projects.metaverse.title': 'Metaverse Web Portal',
    'projects.metaverse.description': 'Web portal for metaverse access with virtual reality and immersive 3D interactions.',
    'footer.brand.description': 'Developing the future with cutting-edge technology and constant innovation',
    'footer.tech.title': 'Technologies',
    'footer.vision.title': 'Vision',
    'footer.vision.description': 'Transform ideas into digital reality through innovative technological solutions that shape the future',
    'footer.madeWith': 'Made with',
    'footer.and': 'and',
    'footer.by': 'by Nova Tech',
    'footer.copyright': '© 2024 Nova Tech. Innovation without limits.',
    'guide.title': 'Aurum',
    'guide.overview.title': 'Overview',
    'guide.overview.description': 'Aurum FrontEnd — Real‑time Investment Dashboard. React frontend for portfolio tracking and real-time quotes, focusing on network resilience, responsive UX and extensible architecture. Integrates WebSockets for market streaming and REST API for secure operations.',
    'guide.architecture.title': 'Architecture and Stack',
    'guide.architecture.stack': 'Stack: React + Vite, Context API + Hooks, Socket.IO Client, Fetch API (retries/timeouts), Tailwind CSS, custom translation structure (PT/EN).',
    'guide.architecture.layers': 'Layers:',
    'guide.architecture.requestMonitor': 'src/components/contexts/RequestMonitorContext.jsx: socket singleton, request deduplication, global timeouts.',
    'guide.architecture.backendClient': 'src/api/backendClient.js: retriable fetch, timeouts, structured error propagation (status, message).',
    'guide.architecture.pages': 'Pages:',
    'guide.architecture.pages.dashboard': 'Dashboard.jsx — Charts with on-visibility updates',
    'guide.architecture.pages.marketTicker': 'MarketTicker.jsx — Real-time marquee tickers with backend-managed requests',
    'guide.architecture.pages.login': 'Login.jsx — Login with credentials/Google Authenticator with error translators/validations from backend',
    'guide.architecture.pages.portfolio': 'Portfolio.jsx — Portfolio with investment details',
    'guide.architecture.pages.liquidityModal': 'LiquidityModal.jsx — Liquidity modal with charts and information about investment liquidity time',
    'guide.architecture.pages.portfolioModal': 'PortfolioModal.jsx — Individual investment details',
    'guide.architecture.pages.addInvestment': 'AddInvestment.jsx — Add investments in crypto, Brazilian and American stocks',
    'guide.architecture.languageContext': 'LanguageContext.jsx: HTTP code translations and generic messages.',
    'guide.features.title': 'Main Features',
    'guide.features.realtime': 'Realtime: Ticker and price updates via Socket.IO (controlled reconnection, backoff, event‑driven).',
    'guide.features.deduplication': 'Request deduplication: same logical key → one call, multiple consumers; 60s global timeout.',
    'guide.features.resilience': 'Network resilience: socket URL fallback, connection wait, consistent 4xx/5xx handling.',
    'guide.features.errors': 'Structured errors + custom translation structure: backend returns (status, message); UI translates by status (ex.: error.401) with fallback.',
    'guide.features.ux': 'UX: loading states, technical message filtering (ex.: hides "socket not connected"), optimized dark mode.',
    'guide.decisions.title': 'Relevant Technical Decisions',
    'guide.decisions.singleton': 'Socket Singleton: isConnectingRef + connected checks prevent duplicate connections.',
    'guide.decisions.timeouts': 'Timeouts and Retries: AbortController/timeouts in fetch; global timeout in WebSocket flows.',
    'guide.decisions.standardized': 'Standardized errors: always throws object with status/message for predictability.',
    'guide.decisions.configuration': 'Robust configuration: getSocketUrl derives fallback from API_URL and environment (dev/prod).',
    'guide.security.title': 'Security and Best Practices',
    'guide.security.keys': 'No keys on client: environment variables; no sensitive logic on frontend.',
    'guide.security.isolation': 'Error isolation: internal messages don\'t leak; UI filters technical noise.',
    'guide.security.architecture': 'Scalable architecture: specialized contexts, pure functions for APIs, decoupled components.',
    'guide.performance.title': 'Metrics and Performance (indicative)',
    'guide.performance.connections': 'Unique WebSocket connections per session/component.',
    'guide.performance.redundancy': 'Reduction of redundant calls with deduplication.',
    'guide.performance.latency': 'Reduced perceived latency via streaming + pre-loading on visibility.',
    'guide.review.title': 'What to review in code (for evaluators)',
    'guide.review.requestMonitor': 'RequestMonitorContext.jsx: socket lifecycle, deduplicated promise maps, timeout cleanup.',
    'guide.review.backendClient': 'backendClient.js: retry policy, timeouts, error normalization.',
    'guide.review.login': 'Login.jsx: HTTP code translation, accessible error UI.',
    'guide.review.config': 'config.js: socketUrl derivation and fallbacks.',
    'guide.screenshots.title': 'Screenshot Guide (suggestion)',
    'guide.screenshots.login': 'Login (PT/EN) — "HTTP error code handling with custom translation structure and dark mode."',
    'guide.screenshots.dashboard': 'Dashboard — "Portfolio summary with visibility-based tab updates."',
    'guide.screenshots.marketTicker': 'Market Ticker — "Real-time quote streaming via Socket.IO with controlled reconnection."',
    'guide.screenshots.liquidityModal': 'Liquidity Modal — "Consistent interactions; fixed closing and clear states."',
    'guide.screenshots.console': 'Console (devtools) — "Request deduplication: same key, one call, multiple consumers."',
    'guide.screenshots.network': 'Network (devtools) — "Functional socketUrl fallback; no duplicate connections."',
    'guide.screenshots.structure': 'Project structure — "Separation of contexts, API client and pages for scalability."',
    'guide.differentials.title': 'Differentials',
    'guide.differentials.robustness': 'Above-average network robustness: avoids socket race conditions, promise hangs and reconnection loops.',
    'guide.differentials.ux': 'Product-level error and UX: user-friendly messages, clear diagnostics for devs.',
    'guide.differentials.evolution': 'Ready for evolution: data provider changes and new features without breaking internal contracts.'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

/* função t sem o typescript
  const t = (key: string): string => {
    const currentTranslations = translations[language];
    return currentTranslations[key] || key;
  }; */

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 